config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items 

  

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  	# index is a GET route
  	# shows all the items 
  	@items = Item.all #grabs all items out of the database
  end

  def show
  	# show is a GET route
  	# responsible for showing a single item or shows more information
  	@item = Item.find(params[:id])
  end

  def new
  	# new is a GET route
  	# responsible for rendering the form to create a new item
  	@item = Item.new #creates a new instance of this item
  end

  def create
  	# create is a POST route
	  # this was later added on because we didn't need to render a view for 'create'
	  # responsible for creating the item and redirecting the user
	  @item = Item.new(item_params)
	   if @item.save
	  	# redirect back to the index page
	  	redirect_to items_path
	  else
	  	# render the new form again and show users errors
	  	render :new
	  end
  end

  def edit
  	# edit is a GET route
  	# responsible for rendering the form so we can edit a single item
  	@item = Item.find(params[:id])
  end

  def update
  	# update is a PUT route
  	# responsible for updating the item and redirecting the user
  	@item = Item.find(params[:id])
  	if @item.update(item_params)
  		# redirect to the show page
  		redirect_to items_path(@items)
  	else
  		# TODO: show errors to user
  		render :edit 
    end
  end

	def destroy
		# destroy is a DELETE route
	  # responsible for finding the item, and removing it from our database
	  item = Item.find(params[:id])
	  if item.destroy
	  	# TODO: put a flash message for better user experience
	  	redirect_to items_path
	  	# redirect back to the index page
	  else
	  	# show an error message
	  	redirect_to items_path(item)
	  	# redirect back to show page 
	  end
	end  

	private 
		def item_params
			params.require(:item).permit(:name, :description, :completed, :priority)
			# require gets the values of the item key and permit certain attributes
		end
	end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<!-- This is now a Partial form that is linked to other files -->
<!-- Rails Helpers -->
<%= form_for @item do |f| %> 
<!-- this is like saying <form action "/items" method="POST"></form> -->
	<%= f.label :name %>
	<!-- <this is like saying label for="name">Name</label> -->
	<%= f.text_field :name %>
	<!-- <this is like saying input type="text" id="name" name="item[name]" /> -->
	<br />
	<%= f.label :description %>
	<!-- <label for="description">Description</label>-->
	<%= f.text_area :description %>
	<!-- <textarea id="description" name="item[description]"></textarea>-->
	<br />
	<%= f.label :completed %>
	<!-- <label for="completed">Completed</label>-->
	<%= f.check_box :completed %>
	<!-- <input type="checkbox" id="completed" name="item[completed]" /> -->
	<br />
	<%= f.label :priority %>
	<%= f.select :priority, [1,2,3,4,5,6,7,8,9,10] %>
	<br />
	<%= f.submit 'Create New Item' %>
	<!-- <input type="submit"> -->
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item With Name: <%= @item.name %></h1>
<br />
<%= render(partial: 'form') %>

app/views/items/index.html.erb
<h1>Items</h1>
<br />
<% if @items.any? %> 
<!-- this is saying if items any then run-->
	<ul>
		<% @items.each do |item| %>
		<li>
			<%= link_to item.name, item_path(item) %>
			<%= button_to 'Edit Item', edit_item_path(item), method: :get %>
			<%= button_to "Delete", item_path(item), method: :delete, data: {confirm: 'Really delete this item?'} %>
		</li>
		<% end %>
	</ul>
	<% else %>
		<h3>No items to show</h3>
<% end %>
<hr />
<%= link_to 'New Item', new_item_path %>
<!-- this is like saying <a href="/items/new">New Item</a>  if you go to terminal and type rake routes will tell you the path needed remember to think verb = path -->

app/views/items/new.html.erb
<h1>Create a new Item</h1>
<br />
<%= render(partial: 'form') %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<br />
<label>Priority:</label>
<p><%= @item.priority %></p>

<label>Description:</label>
<p><%= @item.description %></p>

<label>Completed?:</label>
<p><%= @item.completed %></p>
<hr />
<%= button_to 'Edit Item', edit_item_path(@item), method: :get %>
<%= button_to 'Delete Item', item_path(@item), method: :delete, data: {confirm: 'Really delete this item?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>